dist: trusty
sudo: required
language: node_js
node_js:
  - "10"
os:
  - linux
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: lint
      script:
        - ng lint
    - stage: test
      script:
        - npm run test
        - npm run report-coverage
    - stage: build & publish showcase
      script:
        - npm run build:demo
        - npm run publish:demo
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: dist/resumePage
      if: branch = master
