name: Deploy to GitHub Pages

on:
  push:
    branches: [gh-pages]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3   

        with:
          node-version:   
 '16.x' # Adjust this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses:   
 actions/deploy@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist # Replace with your build output directory
          repo: ${{ github.repository }}
          branch: gh-pages
