name: Build, Lint, and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:demo
      - name: Lint
        run: ng lint

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: Deploy to GitHub Pages
        uses: actions/deploy-github-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist/resumePage
